/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AuthEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordWebhookUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Ec2InstanceId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GitHubToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Tasks": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}